### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by favoyang** [MileyHollenberg/ChangeCameraAimOnStart#1]
Hi @MileyHollenberg,

Thanks for making this awesome UPM package. I'm the creator of the [OpenUPM](https://openupm.com/) platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 300+ open-source UPM packages at the time of writing.

To make your package available on the platform you need create one GitHub release `v1.0.0` (which created a Git tag) based on the master branch. Then you can submit the package [here](https://openupm.com/packages/add/).

**Comment by MileyHollenberg** [comment]
Hey @favoyang ,

Thanks! I've heard of OpenUPM before but haven't used it myself yet. I did a quick check and saw that the dependent package is also available there so it wouldn't be too much work to get it published on OpenUPM as well, I'll have a look at this this weekend.

Quick question beforehand for which I am assuming the answer will be yes, does OpenUPM properly support multiple dependencies? I tried to get this to work with the current Package Manager from Unity but this is something the team is still working on for Github projects which is why I currently have the setup instructions in the Readme

Greets,
Miley

**Comment by MileyHollenberg** [comment]
Hmm, it seems like the Toolbar extender isn't fully available yet, it says it has no install available yet, https://openupm.com/packages/com.marijnzwemmer.unity-toolbar-extender/

Since there's an open issue on his package already for this I'll let him know, once that's taken care of I can add OpenUPM support for this package as well :)

**Comment by favoyang** [comment]
Thanks for the quick reply.

To support custom dependencies, you need add all dependencies to scopes field. OpenUPM-CLI provides such feature by resolving dependencies recursively.

```
openupm add pkgname
```

**Comment by MileyHollenberg** [comment]
I was able to add the dependency through regular git and it seems like OpenUPM is supporting it as is, the release (v1.0.1) is now live so this issue can be closed :)
